### ISSUE TITLE
New PI4 revision.

### ISSUE THREAD

**Issue by bobrol** [besp9510/pi_gpio#1]
Hello
My new PI4 has unsupported revision number in /proc/cpuinfo:
Revision: **d03114**

Could it be added to "get_pi_version.c"? 
It returns -140 error (ENPIOVER) in current library version.

Thanks.

**Comment by besp9510** [comment]
Hi,

It has been added! Pull the latest, reinstall, and it should recognize your Pi now.

If it does, feel free to close the issue ticket.

**Comment by bobrol** [comment]
Thank you.
